### ISSUE TITLE
Fix Lighthouse scores check

### ISSUE THREAD

**Issue by Brandon32** [adobecom/bacom#106]
Because of the VPN changes we can not get lighthouse scores for PRs.
Need to see how to get around this issue or remove the lighthouse check.

**Comment by fullcolorcoder** [comment]
@Brandon32 For PRs that enhance/fix things that exist already in prod, we could use the milolibs=your-repo trick.

**Comment by Brandon32** [comment]
@fullcolorcoder Thanks, that works for Milo branches but we can't test BACOM branches.
Even on the main BACOM branch you get a "Error 401 Unauthorized", right now we are working on a faas-styles branch.

**Comment by Brandon32** [comment]
We have to use published content to test with lighthouse, will update the PR template to reflect this.
